Repository SSUMC-7th/Spring_Boot_A, pull requests merged in 2024-11, with the labels that each got.

#21 [Michelin] Chapter06_JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/Qrestaurant.java
  src/main/generated/umc/spring/domain/Quser.java
  src/main/generated/umc/spring/domain/mapping/Qmission.java
  src/main/generated/umc/spring/domain/mapping/Quser_favorite.java
  src/main/generated/umc/spring/domain/mapping/Quser_mission.java
  src/main/generated/umc/spring/domain/mapping/Quser_review.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/enums/MissionCheck.java
  src/main/java/umc/spring/domain/mapping/user_review.java
  src/main/java/umc/spring/domain/restaurant.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepository.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepositoryCustom.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepositoryImpl.java
  src/main/java/umc/spring/service/RestaurantService/RestaurantQueryService.java
  src/main/java/umc/spring/service/RestaurantService/RestaurantQueryServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Chapter06

#17 [Jerry] Chapter06_JPA 활용
  build.gradle
  src/main/java/umc/study/Application.java
  src/main/java/umc/study/StudyApplication.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/repository/storeRepository/StoreRepository.java
  src/main/java/umc/study/repository/storeRepository/StoreRepositoryCustom.java
  src/main/java/umc/study/repository/storeRepository/StoreRepositoryImpl.java
  src/main/java/umc/study/service/storeService/StoreQueryService.java
  src/main/java/umc/study/service/storeService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#18 [Tania] Chapter06_JPA 활용
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_annotations_2_17_2.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_core_2_17_2.xml
  .idea/libraries/Gradle__com_fasterxml_jackson_core_jackson_databind_2_17_2.xml
  .idea/libraries/Gradle__org_projectlombok_lombok_1_18_34.xml
  .idea/modules.xml
  .idea/modules/spring.iml
  .idea/modules/spring.main.iml
  build.gradle
  build/classes/java/main/umc/spring/Application.class
  build/classes/java/main/umc/spring/domain/Member$MemberBuilder.class
  build/classes/java/main/umc/spring/domain/Member.class
  build/classes/java/main/umc/spring/domain/Mission$MissionBuilder.class
  build/classes/java/main/umc/spring/domain/Mission.class
  build/classes/java/main/umc/spring/domain/Region$RegionBuilder.class
  build/classes/java/main/umc/spring/domain/Region.class
  build/classes/java/main/umc/spring/domain/Restaurant$RestaurantBuilder.class
  build/classes/java/main/umc/spring/domain/Restaurant.class
  build/classes/java/main/umc/spring/domain/Review$ReviewBuilder.class
  build/classes/java/main/umc/spring/domain/Review.class
  build/classes/java/main/umc/spring/domain/common/BaseEntity.class
  build/classes/java/main/umc/spring/domain/enums/Gender.class
  build/classes/java/main/umc/spring/domain/enums/Status.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QRestaurant.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Restaurant.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepository.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepositoryCustom.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepositoryImpl.java
  src/main/java/umc/spring/service/RestaurantService/RestaurantQueryService.java
  src/main/java/umc/spring/service/RestaurantService/RestaurantQueryServiceImpl.java
  src/main/resources/Application.yml
  src/main/resources/application.yml
Labels: ✨ Chapter06

#24 [Tania] Chapter07_API 응답 통일 & 에러 핸들러
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  build.gradle
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/Exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/Exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/Exception/handler/TempHandler.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/tempService/TempCommandService.java
  src/main/java/umc/spring/service/tempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/tempService/TempQueryService.java
  src/main/java/umc/spring/service/tempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#22 [junseoplee] Chapter07_API 응답 통일 & 에러 핸들러
  .gitignore
  build.gradle
  src/main/generated/project/ssumc7thspringboota/domain/QBaseEntity.java
  src/main/generated/project/ssumc7thspringboota/domain/foodtype/QFoodType.java
  src/main/generated/project/ssumc7thspringboota/domain/inquiry/QInquiry.java
  src/main/generated/project/ssumc7thspringboota/domain/inquiry/inquiryphoto/QInquiryPhoto.java
  src/main/generated/project/ssumc7thspringboota/domain/mapping/storefoodtype/QStoreFoodType.java
  src/main/generated/project/ssumc7thspringboota/domain/mapping/usermission/QUserMission.java
  src/main/generated/project/ssumc7thspringboota/domain/mapping/userpreferredfoodtype/QUserPreferredFoodType.java
  src/main/generated/project/ssumc7thspringboota/domain/mission/QMission.java
  src/main/generated/project/ssumc7thspringboota/domain/review/QReview.java
  src/main/generated/project/ssumc7thspringboota/domain/review/reviewphoto/QReviewPhoto.java
  src/main/generated/project/ssumc7thspringboota/domain/store/QStore.java
  src/main/generated/project/ssumc7thspringboota/domain/user/QUser.java
  src/main/java/project/ssumc7thspringboota/Ssumc7thSpringBootAApplication.java
  src/main/java/project/ssumc7thspringboota/api/ApiResponse.java
  src/main/java/project/ssumc7thspringboota/api/GlobalExceptionHandler.java
  src/main/java/project/ssumc7thspringboota/api/apitest/ApiTestController.java
  src/main/java/project/ssumc7thspringboota/api/apitest/request/ApiExceptionTestRequest.java
  src/main/java/project/ssumc7thspringboota/application/apitest/ApiTestService.java
  src/main/java/project/ssumc7thspringboota/application/apitest/request/ApiExceptionTestServiceRequest.java
  src/main/java/project/ssumc7thspringboota/application/apitest/response/ApiTestResponse.java
  src/main/java/project/ssumc7thspringboota/application/store/temp/StoreQueryService.java
  src/main/java/project/ssumc7thspringboota/application/store/temp/StoreQueryServiceImpl.java
  src/main/java/project/ssumc7thspringboota/exception/BusinessException.java
  src/main/java/project/ssumc7thspringboota/exception/ErrorCode.java
  src/main/java/project/ssumc7thspringboota/exception/ErrorResponse.java
Labels: ✨ Chapter07

#39 [Jerry] Chapter 8. API & Swagger & Annotation issue #28
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/study/apiPayload/exception/handler/StoreHandler.java
  src/main/java/umc/study/converter/ReviewConverter.java
  src/main/java/umc/study/converter/StoreConverter.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/repository/reviewRepository/ReviewRepository.java
  src/main/java/umc/study/service/storeService/StoreQueryService.java
  src/main/java/umc/study/service/storeService/StoreQueryServiceImpl.java
  src/main/java/umc/study/web/controller/StoreController.java
  src/main/java/umc/study/web/dto/ReviewRequestDTO.java
  src/main/java/umc/study/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#40 [Jerry] Chapter 8. API & Swagger & Annotation issue #35
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/converter/MemberMissionConverter.java
  src/main/java/umc/study/converter/MemberPreferConverter.java
  src/main/java/umc/study/converter/MissionConverter.java
  src/main/java/umc/study/domain/mapping/MemberMission.java
  src/main/java/umc/study/repository/missionRepository/MissionRepository.java
  src/main/java/umc/study/service/storeService/StoreQueryService.java
  src/main/java/umc/study/service/storeService/StoreQueryServiceImpl.java
  src/main/java/umc/study/web/controller/StoreController.java
  src/main/java/umc/study/web/dto/MissionRequestDTO.java
  src/main/java/umc/study/web/dto/MissionResponseDTO.java
Labels: ✨ Chapter08, :sparkles: feature

#47 [Feature] 내가 작성한 리뷰 목록 API 구현
  build.gradle
  src/main/java/project/ssumc7thspringboota/Ssumc7thSpringBootAApplication.java
  src/main/java/project/ssumc7thspringboota/annotation/CheckPage.java
  src/main/java/project/ssumc7thspringboota/annotation/implement/PageValidator.java
  src/main/java/project/ssumc7thspringboota/api/apitest/ApiTestController.java
  src/main/java/project/ssumc7thspringboota/api/apitest/request/ApiExceptionTestRequest.java
  src/main/java/project/ssumc7thspringboota/api/mapping/usermission/UserMissionController.java
  src/main/java/project/ssumc7thspringboota/api/mission/MissionController.java
  src/main/java/project/ssumc7thspringboota/api/review/ReviewController.java
  src/main/java/project/ssumc7thspringboota/api/store/StoreController.java
  src/main/java/project/ssumc7thspringboota/api/user/UserController.java
  src/main/java/project/ssumc7thspringboota/application/apitest/ApiTestService.java
  src/main/java/project/ssumc7thspringboota/application/apitest/request/ApiExceptionTestServiceRequest.java
  src/main/java/project/ssumc7thspringboota/application/apitest/response/ApiTestResponse.java
  src/main/java/project/ssumc7thspringboota/application/review/ReviewService.java
  src/main/java/project/ssumc7thspringboota/application/review/response/ReviewListResponse.java
  src/main/java/project/ssumc7thspringboota/config/SwaggerConfig.java
  src/main/java/project/ssumc7thspringboota/domain/review/repository/ReviewRepository.java
  src/main/java/project/ssumc7thspringboota/exception/ErrorCode.java
Labels: ✨ Chapter09, Feature

#52 [Feature] 진행 중인 미션 진행 완료로 바꾸기 API 구현
  src/main/java/project/ssumc7thspringboota/api/ApiResponse.java
  src/main/java/project/ssumc7thspringboota/api/mapping/usermission/UserMissionController.java
  src/main/java/project/ssumc7thspringboota/api/mapping/usermission/request/UserMissionCreateRequest.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/UserMissionService.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/request/UserMissionCreateServiceRequest.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/response/UserMissionCompleteResponse.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/response/UserMissionCreateResponse.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/response/UserMissionListResponse.java
  src/main/java/project/ssumc7thspringboota/domain/mapping/usermission/UserMission.java
Labels: ✨ Chapter09, Feature

#54 [junseoplee] Chapter09_API & Paging
  build.gradle
  src/main/java/project/ssumc7thspringboota/Ssumc7thSpringBootAApplication.java
  src/main/java/project/ssumc7thspringboota/api/ApiResponse.java
  src/main/java/project/ssumc7thspringboota/api/GlobalExceptionHandler.java
  src/main/java/project/ssumc7thspringboota/api/apitest/ApiTestController.java
  src/main/java/project/ssumc7thspringboota/api/apitest/request/ApiExceptionTestRequest.java
  src/main/java/project/ssumc7thspringboota/api/mapping/usermission/UserMissionController.java
  src/main/java/project/ssumc7thspringboota/api/mapping/usermission/request/UserMissionCreateRequest.java
  src/main/java/project/ssumc7thspringboota/api/mission/MissionController.java
  src/main/java/project/ssumc7thspringboota/api/review/ReviewController.java
  src/main/java/project/ssumc7thspringboota/api/store/StoreController.java
  src/main/java/project/ssumc7thspringboota/api/user/UserController.java
  src/main/java/project/ssumc7thspringboota/application/apitest/ApiTestService.java
  src/main/java/project/ssumc7thspringboota/application/apitest/request/ApiExceptionTestServiceRequest.java
  src/main/java/project/ssumc7thspringboota/application/apitest/response/ApiTestResponse.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/UserMissionService.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/request/UserMissionCreateServiceRequest.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/response/UserMissionCompleteResponse.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/response/UserMissionCreateResponse.java
  src/main/java/project/ssumc7thspringboota/application/mapping/usermission/response/UserMissionListResponse.java
  src/main/java/project/ssumc7thspringboota/application/mission/MissionService.java
  src/main/java/project/ssumc7thspringboota/application/mission/response/MissionListResponse.java
  src/main/java/project/ssumc7thspringboota/application/review/ReviewService.java
  src/main/java/project/ssumc7thspringboota/application/review/response/ReviewListResponse.java
  src/main/java/project/ssumc7thspringboota/application/store/StoreService.java
  src/main/java/project/ssumc7thspringboota/application/user/UserService.java
  src/main/java/project/ssumc7thspringboota/application/user/implement/UserValidator.java
  src/main/java/project/ssumc7thspringboota/common/annotation/CheckPage.java
  src/main/java/project/ssumc7thspringboota/common/annotation/implement/PageValidator.java
  src/main/java/project/ssumc7thspringboota/common/config/QueryDSLConfig.java
  src/main/java/project/ssumc7thspringboota/common/config/SecurityConfig.java
  src/main/java/project/ssumc7thspringboota/common/config/SwaggerConfig.java
  src/main/java/project/ssumc7thspringboota/common/exception/BusinessException.java
  src/main/java/project/ssumc7thspringboota/common/exception/ErrorCode.java
  src/main/java/project/ssumc7thspringboota/common/exception/ErrorResponse.java
  src/main/java/project/ssumc7thspringboota/domain/mapping/usermission/UserMission.java
  src/main/java/project/ssumc7thspringboota/domain/mapping/usermission/repository/UserMissionRepository.java
  src/main/java/project/ssumc7thspringboota/domain/mission/repository/MissionRepository.java
  src/main/java/project/ssumc7thspringboota/domain/review/repository/ReviewRepository.java
Labels: ✨ Chapter09

#58 [Michelin] Chapter09_API & Paging
  build.gradle
  src/main/generated/umc/spring/domain/mapping/Qmission.java
  src/main/generated/umc/spring/domain/mapping/Quser_favorite.java
  src/main/generated/umc/spring/domain/mapping/Quser_mission.java
  src/main/generated/umc/spring/domain/mapping/Quser_review.java
  src/main/java/umc/spring/config/SwaggerConfig.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/domain/mapping/mission.java
  src/main/java/umc/spring/domain/mapping/user_favorite.java
  src/main/java/umc/spring/domain/mapping/user_mission.java
  src/main/java/umc/spring/domain/mapping/user_review.java
  src/main/java/umc/spring/domain/restaurant.java
  src/main/java/umc/spring/domain/user.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/repository/UserMissionRepository.java
  src/main/java/umc/spring/repository/UserRepository.java
  src/main/java/umc/spring/service/MissionQueryService.java
  src/main/java/umc/spring/service/MissionQueryServiceImpl.java
  src/main/java/umc/spring/service/StoreQueryService.java
  src/main/java/umc/spring/service/StoreQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistRestaurant.java
  src/main/java/umc/spring/validation/validator/RestaurantExistValidator.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter09
