Repository SSUMC-7th/Spring_Boot_A, pull requests merged in 2024-10, with the labels that each got.

#2 [junseoplee] Chapter01_Database 설계
  src/main/java/project/ssumc7thspringboota/Ssumc7thSpringBootAApplication.java
  src/main/java/project/ssumc7thspringboota/domain/BaseEntity.java
  src/main/java/project/ssumc7thspringboota/domain/foodtype/FoodType.java
  src/main/java/project/ssumc7thspringboota/domain/inquiry/Inquiry.java
  src/main/java/project/ssumc7thspringboota/domain/inquiryphoto/InquiryPhoto.java
  src/main/java/project/ssumc7thspringboota/domain/mission/Mission.java
  src/main/java/project/ssumc7thspringboota/domain/review/Review.java
  src/main/java/project/ssumc7thspringboota/domain/reviewphoto/ReviewPhoto.java
  src/main/java/project/ssumc7thspringboota/domain/store/Store.java
  src/main/java/project/ssumc7thspringboota/domain/storefoodtype/StoreFoodType.java
  src/main/java/project/ssumc7thspringboota/domain/user/User.java
  src/main/java/project/ssumc7thspringboota/domain/usermission/UserMission.java
  src/main/java/project/ssumc7thspringboota/domain/userpreferredfoodtype/UserPreferredFoodType.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Chapter01

#4 [junseoplee] Chapter 4. Spring Boot의 코어 개념
  src/main/resources/application.yml
Labels: ✨ Chapter04

#6 [Tania] Chapter 4. Spring Boot의 코어 개념
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/spring/Application.java
  src/main/resources/application.yml
  src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter04

#5 [Jerry] Chapter 4. Spring Boot의 코어 개념
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/spring/Application.java
  src/main/resources/application.yml
  src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter04

#12 [Jerry] Chapter 5. JPA 기초 및 프로젝트 구조
  src/main/java/umc/study/Application.java
  src/main/java/umc/study/domain/FoodCategory.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Region.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/Terms.java
  src/main/java/umc/study/domain/common/BaseEntity.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/enums/MemberStatus.java
  src/main/java/umc/study/domain/enums/MissionStatus.java
  src/main/java/umc/study/domain/enums/SocialType.java
  src/main/java/umc/study/domain/mapping/MemberAgree.java
  src/main/java/umc/study/domain/mapping/MemberMission.java
  src/main/java/umc/study/domain/mapping/MemberPrefer.java
  src/main/resources/application.yml
Labels: ✨ Chapter05

#11 [junseoplee] Chapter05_JPA 기초 및 프로젝트 구조
  src/main/java/project/ssumc7thspringboota/Ssumc7thSpringBootAApplication.java
  src/main/java/project/ssumc7thspringboota/domain/foodtype/FoodType.java
  src/main/java/project/ssumc7thspringboota/domain/inquiry/Inquiry.java
  src/main/java/project/ssumc7thspringboota/domain/inquiry/inquiryphoto/InquiryPhoto.java
  src/main/java/project/ssumc7thspringboota/domain/mapping/storefoodtype/StoreFoodType.java
  src/main/java/project/ssumc7thspringboota/domain/mapping/usermission/UserMission.java
  src/main/java/project/ssumc7thspringboota/domain/mapping/userpreferredfoodtype/UserPreferredFoodType.java
  src/main/java/project/ssumc7thspringboota/domain/mission/Mission.java
  src/main/java/project/ssumc7thspringboota/domain/review/Review.java
  src/main/java/project/ssumc7thspringboota/domain/review/reviewphoto/ReviewPhoto.java
  src/main/java/project/ssumc7thspringboota/domain/store/Store.java
  src/main/java/project/ssumc7thspringboota/domain/user/User.java
Labels: ✨ Chapter05
